### ISSUE TITLE
LISA sensitivity is overestimated

### ISSUE THREAD

**Issue by jacopok** [janosch314/GWFish#77]
The new sensitivity curves are from [this paper](https://arxiv.org/pdf/2108.01167.pdf).

They report some test cases: for example, the first row of Test Case 1 on page 31 is a BBH with source-frame individual masses of $10^5$, at $z=1$. The recovered SNR they find is something like 1100-1200.

The current implementation of the LISA sensitivity in GWFish overestimates this by roughly a factor 10:

```python
from GWFish.modules.horizon import compute_SNR, Planck18
from GWFish.modules.detection import Detector

z = 1
params = {
    'luminosity_distance': Planck18.luminosity_distance(z).value,
    'mass_1': 1e5 * (1+z), 
    'mass_2': 1e5 * (1+z), 
    'theta_jn': 0,
    'ra': 1,
    'dec': -0.5,
    'psi': 0.,
    'phase': 0.,
    'geocent_time': 1187008882.4,
}

snr = compute_SNR(params, Detector('LISA'))
print(snr)
```
The result is 12009.

**Comment by jacopok** [comment]
@janosch314 I never looked into the [`projection_solarorbit`](https://github.com/janosch314/GWFish/blob/main/GWFish/modules/detection.py#L423) function in detail, but it seems like it's only using the first component of LISA (I only see references to `components[0]`), could that be related to the problem?

**Comment by janosch314** [comment]
After updating the LISA noise model, I introduced a bug by not modifying line 447. It currently reads
proj[in_band_slice, :] = doppler_to_strain * AET(polarizations[in_band_slice, :], eij, theta, ra, psi, components[0].L, ff)

but it should read
proj[in_band_slice, :] = AET(polarizations[in_band_slice, :], eij, theta, ra, psi, components[0].L, ff)
