### ISSUE TITLE
"fishermatrix.py" : Fixed waveform_model & waveorm_class in compute_detector_fisher & compute_network_errors functions

### ISSUE THREAD

**Issue by AlessandroAgapito23** [janosch314/GWFish#80]
The waveform inputs (waveform_model, waveorm_class) of these functions (compute_detector_fisher, compute_network_errors) are fixed and they cannot be passed through other scripts. The waveform_model has been fixed in the "waveforms.py" module and the waveform_class has been fixed to "wf.LALFD_waveform". If not specified there could be some troubles.

**Comment by jacopok** [comment]
Hi! I'm not sure I understand what you're referring to: as documented [here](https://gwfish.readthedocs.io/en/latest/reference/API.html), the functions you mention take a  `waveform_model` and `waveform_class` input, which changes the waveform used to compute the Fisher matrix. They do have a default value, specified in `waveforms.py`, but that is only used for convenience when the waveform inputs are not given.

If that seems to not be working for you, could you provide a code example of what goes wrong?
